using System;
using System.Security;
using System.Text;

namespace ChristianHelle.DeveloperTools.CodeGenerators.Resw.VSPackage.WinUI.CodeGeneration;

/// <summary>
/// Generates a WinUI 3-compatible, strongly-typed C# helper class from the
/// resources defined in a .resw file.
///
/// <para>
/// Unlike the UWP (Universal Windows Platform) ResourceLoader APIs, WinUI 3 uses
/// <c>Microsoft.Windows.ApplicationModel.Resources.ResourceLoader</c> from the
/// Windows App SDK. This class generates code that targets those APIs.
/// </para>
///
/// <para>
/// The generated class provides:
/// <list type="bullet">
///   <item>A static <c>Resource</c> property that lazily creates the ResourceLoader.</item>
///   <item>A static <c>Initialize()</c> method that can be called explicitly.</item>
///   <item>One static string property per resource key.</item>
/// </list>
/// </para>
/// </summary>
public sealed class WinUICodeGenerator
{
    private readonly string fileContents;
    private readonly string className;
    private readonly string namespaceName;

    /// <param name="fileContents">The raw XML content of the .resw file.</param>
    /// <param name="className">
    ///   The name of the generated class (usually the .resw filename without extension).
    /// </param>
    /// <param name="namespaceName">The default namespace of the containing project.</param>
    public WinUICodeGenerator(string fileContents, string className, string namespaceName)
    {
        this.fileContents = fileContents ?? throw new ArgumentNullException(nameof(fileContents));
        this.className = className ?? throw new ArgumentNullException(nameof(className));
        this.namespaceName = namespaceName ?? throw new ArgumentNullException(nameof(namespaceName));
    }

    /// <summary>Generates and returns the C# source code string.</summary>
    public string GenerateCode()
    {
        var parser = new ResourceParser(fileContents);
        var resources = parser.Parse();

        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// ---------------------------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     This code was generated by ResW File Code Generator (http://bit.ly/reswcodegen)");
        sb.AppendLine("//     ResW File Code Generator was written by Christian Resma Helle");
        sb.AppendLine("//     and is under GNU General Public License version 2 (GPLv2)");
        sb.AppendLine("//");
        sb.AppendLine("//     This code contains a helper class exposing property representations");
        sb.AppendLine("//     of the string resources defined in the specified .ResW file");
        sb.AppendLine("//");
        sb.AppendLine("//     Code generation environment:");
        sb.AppendLine($"//         Time and Date: {DateTime.Now:G} {TimeZoneInfo.Local.DisplayName}");
        sb.AppendLine($"//         Computer Name: {Environment.ExpandEnvironmentVariables("%COMPUTERNAME%.%USERDNSDOMAIN%").ToLower()}");
        sb.AppendLine($"//         User Name    : {Environment.ExpandEnvironmentVariables("%USERDOMAIN%\\%USERNAME%")}");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("// ---------------------------------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public static partial class {className}");
        sb.AppendLine("    {");

        // Private backing field for the ResourceLoader
        sb.AppendLine($"        private static global::Microsoft.Windows.ApplicationModel.Resources.ResourceLoader resourceLoader;");
        sb.AppendLine();

        // Resource property
        sb.AppendLine("        /// <summary>Get or set ResourceLoader implementation</summary>");
        sb.AppendLine($"        public static global::Microsoft.Windows.ApplicationModel.Resources.ResourceLoader Resource");
        sb.AppendLine("        {");
        sb.AppendLine("            get");
        sb.AppendLine("            {");
        sb.AppendLine("                if (resourceLoader == null)");
        sb.AppendLine("                    Initialize();");
        sb.AppendLine("                return resourceLoader;");
        sb.AppendLine("            }");
        sb.AppendLine("            set { resourceLoader = value; }");
        sb.AppendLine("        }");
        sb.AppendLine();

        // Initialize method
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Initializes the ResourceLoader. Call this once at application startup,");
        sb.AppendLine("        /// or let it be called automatically on first access to any resource property.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static void Initialize()");
        sb.AppendLine("        {");
        sb.AppendLine($"            resourceLoader = new global::Microsoft.Windows.ApplicationModel.Resources.ResourceLoader(\"{className}\");");
        sb.AppendLine("        }");

        // One property per resource key
        foreach (var item in resources)
        {
            if (string.IsNullOrEmpty(item.Name))
                continue;

            var propertyName = item.Name.Replace(".", "_").Trim();

            // Dotted keys (e.g. "Button.Text") are accessed as "Button/Text" in WinUI 3
            var resourceKey = item.Name.Replace(".", "/");

            sb.AppendLine();
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// Localized resource similar to \"{SecurityElement.Escape(item.Value ?? item.Name)}\"");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        public static string {propertyName} => Resource.GetString(\"{resourceKey}\");");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
