using ChristianHelle.DeveloperTools.CodeGenerators.Resw.VSPackage.WinUI.CodeGeneration;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace ChristianHelle.DeveloperTools.CodeGenerators.Resw.VSPackage.WinUI.Tests;

[TestClass]
public class WinUICodeGeneratorTests
{
    private const string SampleResw = """
        <?xml version="1.0" encoding="utf-8"?>
        <root>
          <data name="Test1" xml:space="preserve">
            <value>Test 1 value</value>
            <comment>Test 1 comment</comment>
          </data>
          <data name="Test2" xml:space="preserve">
            <value>Test 2 value</value>
          </data>
          <data name="TestControl.Text" xml:space="preserve">
            <value>TestControl.Text value</value>
          </data>
        </root>
        """;

    private const string ClassName = "Resources";
    private const string Namespace = "TestApp";

    private readonly WinUICodeGenerator generator;
    private readonly string generatedCode;

    public WinUICodeGeneratorTests()
    {
        generator = new WinUICodeGenerator(SampleResw, ClassName, Namespace);
        generatedCode = generator.GenerateCode();
    }

    [TestMethod]
    public void GenerateCodeDoesNotReturnNull()
    {
        Assert.IsNotNull(generatedCode);
    }

    [TestMethod]
    public void GeneratedCodeIsNotEmpty()
    {
        Assert.IsFalse(string.IsNullOrWhiteSpace(generatedCode));
    }

    [TestMethod]
    public void GeneratedCodeContainsAutoGeneratedHeader()
    {
        StringAssert.Contains(generatedCode, "<auto-generated>");
        StringAssert.Contains(generatedCode, "http://bit.ly/reswcodegen");
    }

    [TestMethod]
    public void GeneratedCodeContainsCorrectNamespace()
    {
        StringAssert.Contains(generatedCode, $"namespace {Namespace}");
    }

    [TestMethod]
    public void GeneratedCodeContainsCorrectClassName()
    {
        StringAssert.Contains(generatedCode, $"public static partial class {ClassName}");
    }

    [TestMethod]
    public void GeneratedCodeUsesWinUI3ResourceLoader()
    {
        StringAssert.Contains(
            generatedCode,
            "global::Microsoft.Windows.ApplicationModel.Resources.ResourceLoader");
    }

    [TestMethod]
    public void GeneratedCodeDoesNotUseUwpResourceLoader()
    {
        // The UWP ResourceLoader APIs use static factory methods
        // (GetForCurrentView / GetForViewIndependentUse) that don't exist in WinUI 3.
        // Verify those UWP-only call patterns are absent.
        Assert.IsFalse(
            generatedCode.Contains("GetForCurrentView"),
            "Generated code should not use UWP ResourceLoader.GetForCurrentView.");
        Assert.IsFalse(
            generatedCode.Contains("GetForViewIndependentUse"),
            "Generated code should not use UWP ResourceLoader.GetForViewIndependentUse.");
    }

    [TestMethod]
    public void GeneratedCodeDoesNotUseCoreWindow()
    {
        Assert.IsFalse(
            generatedCode.Contains("CoreWindow"),
            "WinUI 3 generated code must not depend on Windows.UI.Core.CoreWindow.");
    }

    [TestMethod]
    public void GeneratedCodeContainsInitializeMethod()
    {
        StringAssert.Contains(generatedCode, "public static void Initialize()");
        StringAssert.Contains(generatedCode, $"new global::Microsoft.Windows.ApplicationModel.Resources.ResourceLoader(\"{ClassName}\")");
    }

    [TestMethod]
    public void GeneratedCodeContainsResourceProperty()
    {
        StringAssert.Contains(generatedCode, "public static global::Microsoft.Windows.ApplicationModel.Resources.ResourceLoader Resource");
    }

    [TestMethod]
    public void GeneratedCodeContainsPropertiesForEachResourceKey()
    {
        StringAssert.Contains(generatedCode, "public static string Test1");
        StringAssert.Contains(generatedCode, "public static string Test2");
    }

    [TestMethod]
    public void GeneratedCodeReplacesDottedKeysWithForwardSlashInGetString()
    {
        // "TestControl.Text" key should be accessed as "TestControl/Text"
        StringAssert.Contains(generatedCode, "GetString(\"TestControl/Text\")");
    }

    [TestMethod]
    public void GeneratedCodeReplacesDottedKeysWithUnderscoreInPropertyName()
    {
        // "TestControl.Text" key should become property "TestControl_Text"
        StringAssert.Contains(generatedCode, "public static string TestControl_Text");
    }

    [TestMethod]
    public void GeneratedCodeContainsSummaryCommentsWithResourceValues()
    {
        StringAssert.Contains(generatedCode, "Localized resource similar to \"Test 1 value\"");
        StringAssert.Contains(generatedCode, "Localized resource similar to \"Test 2 value\"");
    }

    [TestMethod]
    public void GeneratedCodeCallsGetStringWithCorrectKeys()
    {
        StringAssert.Contains(generatedCode, "GetString(\"Test1\")");
        StringAssert.Contains(generatedCode, "GetString(\"Test2\")");
    }

    [TestMethod]
    [ExpectedException(typeof(ArgumentNullException))]
    public void ConstructorThrowsWhenFileContentsIsNull()
    {
        _ = new WinUICodeGenerator(null!, ClassName, Namespace);
    }

    [TestMethod]
    [ExpectedException(typeof(ArgumentNullException))]
    public void ConstructorThrowsWhenClassNameIsNull()
    {
        _ = new WinUICodeGenerator(SampleResw, null!, Namespace);
    }

    [TestMethod]
    [ExpectedException(typeof(ArgumentNullException))]
    public void ConstructorThrowsWhenNamespaceIsNull()
    {
        _ = new WinUICodeGenerator(SampleResw, ClassName, null!);
    }
}
