name: VSIX

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/workflows/**'
      - '!.github/workflows/vsix.yml'
      - 'images/**'
      - 'README.md'
      - 'LICENSE'
      - 'src/publish-manifest.json'
      - 'src/publish.ps1'
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  VERSION: 1.8.0.${{ github.run_number }}

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v5

    - name: Update Versions
      run: >
        ((Get-Content -Path VSPackage/source.extension.vsixmanifest -Raw) -Replace "1.0.0", "${{ env.VERSION }}") | Set-Content -Path VSPackage/source.extension.vsixmanifest;
        ((Get-Content -Path VSPackage/Properties/AssemblyInfo.cs -Raw) -Replace "1.0.0.0", "${{ env.VERSION }}") | Set-Content -Path VSPackage/Properties/AssemblyInfo.cs;
      working-directory: src
      shell: pwsh

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.3

    - name: Restore
      run: msbuild /property:Configuration=Release /t:Restore
      working-directory: .

    - name: Build
      run: msbuild /property:Configuration=Release /t:Rebuild
      working-directory: .

    - name: Move build output
      run: mv src/VSPackage/bin/Release/ResWFileCodeGenerator.vsix ResWFileCodeGenerator-${{ env.VERSION }}.vsix

    - name: Publish artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Artifacts
        path: |
          *.vsix
          docs/Marketplace.md

    - name: Publish to Open VSIX Gallery
      if: github.ref == 'refs/heads/master'
      run: |
        (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
        Vsix-PushArtifacts
        Vsix-PublishToGallery -path ResWFileCodeGenerator-${{ env.VERSION }}.vsix -readmeUrl https://raw.githubusercontent.com/christianhelle/reswcodegen/master/docs/Marketplace.md
      shell: pwsh
      continue-on-error: true
